name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build docker image
        run: |
          cd debian && \
          docker build -t usbsas-builder:debian -f Dockerfile .
      - name: cargo fmt
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo fmt
      - name: cargo clippy
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo clippy
      - name: cargo audit
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo audit
      - name: build usbsas
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo build --release --all --verbose
      - name: tests
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo test --release --all --verbose --exclude usbsas-server
      - name: rebuild usbsas for integration tests
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo build --release --all --verbose --features mock,integration-tests
      - name: integration tests
        run: |
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/:/SRC  \
          --env CARGO_HOME=/SRC/target/.cargo usbsas-builder:debian \
          cargo test --release --verbose -p usbsas-server --features integration-tests
